### ISSUE TITLE
Update gem to use v2 SHARE API

### ISSUE THREAD

**Issue by dbrower** [projecthydra-labs/share_notify#11]
Support v2 of the SHARE API. 

References:

* http://share-research.readthedocs.io/en/latest/share_api.html#push-data-directly-into-the-share-database
* https://share.osf.io/api/v2/

**Comment by awead** [comment]
@dbrower Can we close this?

**Comment by dbrower** [comment]
Yeah, I think the gem supports enough of the new API.
