### ISSUE TITLE
Should support deletion of documents

### ISSUE THREAD

**Issue by carolyncole** [projecthydra-labs/share_notify#4]
There is a new deletion section, which the gem should support.
https://osf.io/dajtq/wiki/Push%20API/

**Comment by awead** [comment]
Nice. They must have just added that.

**Comment by mcritchlow** [comment]
:+1: i can definitely see that coming in handy

**Comment by carolyncole** [comment]
@awead Yes they just added it, when we asked them how to do it.

**Comment by awead** [comment]
great!

**Comment by awead** [comment]
Fixed in 0.2.0.
